enum SearchItemType {
    None = 0
    ConnectionType = 1
    ContactReference = 2
    CreationDate = 3
    CustomField = 4
    Description = 5
    Domain = 6
    Group = 7
    Host = 8
    IsFavorite = 9
    Keywords = 10
    LastUpdateDate = 11
    Name = 12
    OS = 13
    PasswordStrength = 14
    SecurityGroup = 15
    SerialNumber = 16
    ServerRole = 17
    Status = 18
    Username = 19
    Url = 20
    Version = 21
    IP = 22
    MAC = 23
}