name: Publish to PS Gallery

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency: publish_ps_gallery

jobs:
  psgallery-publish:
    name: Publish to PS Gallery
    runs-on: ubuntu-latest
    environment: psgallery-publish

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Publish to PS Gallery
        uses: devolutions/actions/powershell-publish@master
        with:
          nugetApiKey: ${{ secrets.PSGALLERY_API_KEY }}
          modulePath: "'Powershell Module/Devolutions.Server'"
