name: Publish to PS Gallery

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency: publish_ps_gallery

jobs:
  psgallery-publish:
    environment: psgallery-publish
    name: Publish to PS Gallery
    runs-on: ubuntu-latest

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Publish to PS Gallery
        run: Publish-Module -Path 'Powershell Module/Devolutions.Server' -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }} -Verbose
